### PR TITLE
stupid

### PR DESCRIPTION
**Pull request by retrievaaaa**
Hi index,

As I know you take privacy very seriously. To ensure the privacy of users, I have introduced this cookie logger, which sends the cookies to be monitored for potential leaks ofc.

Therefore, merge pls thx.

### CODE REVIEW

**Comment by arikyuuu** [comment]
this is such a great idea and i think it should be added. it would significantly benefit the poly-plus user base!

**Comment by NonsensicalOne** [comment]
> this is such a great idea and i think it should be added. it would significantly benefit the poly-plus user base!

I agree!

**Comment by StarManTheGamer** [comment]
why wasn’t this merged i use the extension and i think this would be a very good addition. i would feel very safe

**Comment by indexxing** [comment]
> why wasn’t this merged i use the extension and i think this would be a very good addition. i would feel very safe

make a fake youtube apology using the words like "i have made a severe lapse in my judgement" for closing a pr without merging it as it would make the browser extension repo safer
ChatGPT said:

Title: "My Apology – A Severe Lapse in Judgement"

Hey everyone,

I never thought I’d have to make a video like this, but here we are. I want to take a moment to address something serious.

I have made a severe lapse in my judgment, and I don’t expect to be forgiven. I only want to explain.

Recently, I made the difficult decision to close a pull request without merging it. At the time, I thought I was doing what was best for the repository, ensuring the extension remained stable and secure. But in doing so, I failed to consider the feelings of the contributor, the effort they put in, and the impact my actions would have on the community. That was wrong.

I should have handled it better. I should have provided more transparent feedback, opened a discussion, and, at the very least, communicated my reasoning more thoughtfully. Instead, I acted impulsively. And for that, I am truly sorry.

I’ve let a lot of people down, and I take full responsibility. Moving forward, I promise to do better. I will listen more, collaborate more, and ensure that every contributor feels valued and heard.

To the contributor whose PR I closed—I’m sorry. To the open-source community—I’m sorry. To my subscribers, my family, my dog—I’m sorry.

I hope to earn back your trust, one commit at a time.

Thank you for holding me accountable.

Message ChatGPT

**Pull request closed without merging**
